In [1]:
import pandas as pd
data = pd.read_csv("dataset/stud_testing_final_updated.csv")
data
df = data.copy()
df[:8]

,Drawing,Dancing,Singing,Sports,VideoGame,Acting,Travelling,Gardening,Animals,Photography,...,Engeeniering,Doctor,Pharmisist,Cycling,Knitting,Director,Journalism,Bussiness,ListeningMusic,Courses
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,BBA- Bachelor of Business Administration
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,BEM- Bachelor of Event Management
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Integrated Law Course- BA + LL.B
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,BJMC- Bachelor of Journalism and Mass Communic...
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,BFD- Bachelor of Fashion Designing
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,BBS- Bachelor of Business Studies
6,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,BTTM- Bachelor of Travel and Tourism Management
7,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,BVA- Bachelor of Visual Arts

In [2]:
df.columns

Index(['Drawing', 'Dancing', 'Singing', 'Sports', 'VideoGame', 'Acting',
       'Travelling', 'Gardening', 'Animals', 'Photography', 'Teaching',
       'Exercise', 'Coding', 'ElectricityComponents', 'MechanicParts',
       'ComputerParts', 'Researching', 'Architecture', 'HistoricCollection',
       'Botany', 'Zoology', 'Physics', 'Accounting', 'Economics', 'Sociology',
       'Geography', 'Psycology', 'History', 'Science', 'BussinessEducation',
       'Chemistry', 'Mathematics', 'Biology', 'Makeup', 'Designing',
       'ContentWriting', 'Crafting', 'Literature', 'Reading', 'Cartooning',
       'Debating', 'Asrtology', 'Hindi', 'French', 'English', 'Urdu',
       'OtherLanguage', 'SolvingPuzzles', 'Gymnastics', 'Yoga', 'Engeeniering',
       'Doctor', 'Pharmisist', 'Cycling', 'Knitting', 'Director', 'Journalism',
       'Bussiness', 'ListeningMusic', 'Courses'],
      dtype='object')

In [3]:
df['Courses'].unique()

array(['BBA- Bachelor of Business Administration',
       'BEM- Bachelor of Event Management',
       'Integrated Law Course- BA + LL.B',
       'BJMC- Bachelor of Journalism and Mass Communication',
       'BFD- Bachelor of Fashion Designing',
       'BBS- Bachelor of Business Studies',
       'BTTM- Bachelor of Travel and Tourism Management',
       'BVA- Bachelor of Visual Arts', 'BA in History',
       'B.Arch- Bachelor of Architecture',
       'BCA- Bachelor of Computer Applications',
       'B.Sc.- Information Technology', 'B.Sc- Nursing',
       'BPharma- Bachelor of Pharmacy', 'BDS- Bachelor of Dental Surgery',
       'Animation, Graphics and Multimedia', 'B.Sc- Applied Geology',
       'B.Sc.- Physics', 'B.Sc. Chemistry', 'B.Sc. Mathematics',
       'B.Tech.-Civil Engineering',
       'B.Tech.-Computer Science and Engineering',
       'B.Tech.-Electronics and Communication Engineering',
       'B.Tech.-Electrical and Electronics Engineering',
       'B.Tech.-Mechanical Engineering', 'B.Com- Bachelor of Commerce',
       'BA in Economics', 'CA- Chartered Accountancy',
       'CS- Company Secretary', 'Diploma in Dramatic Arts', 'MBBS',
       'Civil Services', 'BA in English', 'BA in Hindi', 'B.Ed.'],
      dtype=object)

In [4]:
df['Courses'].value_counts()

Courses
Civil Services                                         21
B.Tech.-Mechanical Engineering                         21
B.Sc.- Physics                                         21
BA in English                                          20
BFD- Bachelor of Fashion Designing                     20
BBA- Bachelor of Business Administration               20
BDS- Bachelor of Dental Surgery                        18
BPharma- Bachelor of Pharmacy                          18
BJMC- Bachelor of Journalism and Mass Communication    17
CS- Company Secretary                                  17
B.Tech.-Electrical and Electronics Engineering         16
BTTM- Bachelor of Travel and Tourism Management        16
CA- Chartered Accountancy                              16
B.Tech.-Civil Engineering                              16
BEM- Bachelor of Event Management                      15
Animation, Graphics and Multimedia                     15
BA in Hindi                                            15
B.Sc- Nursing                                          14
B.Arch- Bachelor of Architecture                       14
B.Sc- Applied Geology                                  14
B.Com- Bachelor of Commerce                            13
B.Tech.-Electronics and Communication Engineering      13
B.Ed.                                                  13
B.Sc.- Information Technology                          13
Diploma in Dramatic Arts                               12
BBS- Bachelor of Business Studies                      12
BCA- Bachelor of Computer Applications                 12
B.Sc. Chemistry                                        12
BA in Economics                                        12
B.Tech.-Computer Science and Engineering               11
BA in History                                          11
BVA- Bachelor of Visual Arts                           10
Integrated Law Course- BA + LL.B                        9
MBBS                                                    9
B.Sc. Mathematics                                       8
Name: count, dtype: int64

In [5]:
df.shape

(514, 60)

In [6]:
course_serials = {
    'BBA- Bachelor of Business Administration': 0,
    'BEM- Bachelor of Event Management': 1,
    'Integrated Law Course- BA + LL.B': 2,
    'BJMC- Bachelor of Journalism and Mass Communication': 3,
    'BFD- Bachelor of Fashion Designing': 4,
    'BBS- Bachelor of Business Studies': 5,
    'BTTM- Bachelor of Travel and Tourism Management': 6,
    'BVA- Bachelor of Visual Arts': 7,
    'BA in History': 8,
    'B.Arch- Bachelor of Architecture': 9,
    'BCA- Bachelor of Computer Applications': 10,
    'B.Sc.- Information Technology': 11,
    'B.Sc- Nursing': 12,
    'BPharma- Bachelor of Pharmacy': 13,
    'BDS- Bachelor of Dental Surgery': 14,
    'Animation, Graphics and Multimedia': 15,
    'B.Sc- Applied Geology': 16,
    'B.Sc.- Physics': 17,
    'B.Sc. Chemistry': 18,
    'B.Sc. Mathematics': 19,
    'B.Tech.-Civil Engineering': 20,
    'B.Tech.-Computer Science and Engineering': 21,
    'B.Tech.-Electronics and Communication Engineering': 22,
    'B.Tech.-Electrical and Electronics Engineering': 23,
    'B.Tech.-Mechanical Engineering': 24,
    'B.Com- Bachelor of Commerce': 25,
    'BA in Economics': 26,
    'CA- Chartered Accountancy': 27,
    'CS- Company Secretary': 28,
    'Diploma in Dramatic Arts': 29,
    'MBBS': 30,
    'Civil Services': 31,
    'BA in English': 32,
    'BA in Hindi': 33,
    'B.Ed.': 34
}


df['Courses'] = df['Courses'].map(course_serials)

In [7]:
df.head()

,Drawing,Dancing,Singing,Sports,VideoGame,Acting,Travelling,Gardening,Animals,Photography,...,Engeeniering,Doctor,Pharmisist,Cycling,Knitting,Director,Journalism,Bussiness,ListeningMusic,Courses
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,3
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,4

In [8]:
from imblearn.over_sampling import SMOTE

In [9]:
df['Courses'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [10]:
df.tail()

,Drawing,Dancing,Singing,Sports,VideoGame,Acting,Travelling,Gardening,Animals,Photography,...,Engeeniering,Doctor,Pharmisist,Cycling,Knitting,Director,Journalism,Bussiness,ListeningMusic,Courses
509,1,0,0,0,1,1,0,0,0,1,...,0,1,1,1,1,1,1,1,1,8
510,1,1,0,1,0,1,1,1,1,0,...,1,1,1,0,1,0,0,0,1,14
511,0,1,0,1,1,0,1,0,0,0,...,1,1,1,0,0,0,1,1,1,8
512,1,0,1,1,1,1,1,0,1,0,...,1,1,1,0,1,0,0,1,1,32
513,1,1,0,1,0,0,0,0,1,1,...,0,0,1,0,1,0,1,0,0,24

In [11]:
smote = SMOTE(random_state = 42)

X = df.drop('Courses', axis=1)
y = df['Courses']

X_resampled, y_resampled = smote.fit_resample(X,y)

In [12]:
# df['Courses'].unique()

In [13]:
X_resampled

,Drawing,Dancing,Singing,Sports,VideoGame,Acting,Travelling,Gardening,Animals,Photography,...,Yoga,Engeeniering,Doctor,Pharmisist,Cycling,Knitting,Director,Journalism,Bussiness,ListeningMusic
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
730,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
731,0,0,1,0,0,0,1,0,1,0,...,0,0,0,1,0,0,0,0,0,1
732,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
733,0,0,0,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,1,1,1
734,0,0,0,0,0,0,1,0,0,0,...,1,1,0,0,1,0,0,0,0,0

In [14]:
y_resampled

0       0
1       1
2       2
3       3
4       4
       ..
730    34
731    34
732    34
733    34
734    34
Name: Courses, Length: 735, dtype: int64

In [15]:
y_resampled.value_counts()

Courses
0     21
1     21
2     21
3     21
4     21
5     21
6     21
7     21
8     21
9     21
10    21
11    21
12    21
13    21
14    21
15    21
16    21
17    21
18    21
19    21
20    21
21    21
22    21
23    21
24    21
25    21
26    21
27    21
28    21
29    21
30    21
31    21
32    21
33    21
34    21
Name: count, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state = 42)

In [17]:
from sklearn.preprocessing import StandardScaler
scaler  =StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings("ignore")

In [19]:
models = {
    "Logistic Regression": LogisticRegression(),
    "Support Vector Classifier" : SVC(),
    "Random Forest Classifier": RandomForestClassifier(),
    "K Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Gaussian Naive Bayes" : GaussianNB(),
    "AdaBoost Classifier" : AdaBoostClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    "XGBoost Classifier": XGBClassifier(use_label_encoder=False, eval_metric='mlogloss') 
}

In [20]:
for name, model in models.items():
    print("="*50)
    print("\n\nModel = ", name) 

    model.fit(X_train_scaled, y_train)

    y_pred = model.predict(X_test_scaled)

    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)

    conf_matrix = confusion_matrix(y_test, y_pred)

    print("Accuracy = ", accuracy)
    print("\nClassification Report :\n", classification_rep)
    print("\nConfusion matrix: \n", conf_matrix)

==================================================


Model =  Logistic Regression
Accuracy =  0.272108843537415

Classification Report :
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.40      0.40      0.40         5
           2       1.00      0.50      0.67         6
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         2
           5       0.50      0.14      0.22         7
           6       0.33      0.17      0.22         6
           7       0.33      0.50      0.40         2
           8       0.00      0.00      0.00         3
           9       0.40      0.67      0.50         3
          10       0.20      0.33      0.25         3
          11       0.20      0.25      0.22         4
          12       0.00      0.00      0.00         6
          13       0.20      0.14      0.17         7
          14       0.40      0.40      0.40         5
          15       0.00      0.00      0.00         2
          16       0.40      0.67      0.50         3
          17       0.00      0.00      0.00         4
          18       0.20      0.50      0.29         4
          19       0.60      0.60      0.60         5
          20       0.00      0.00      0.00         7
          21       0.20      0.50      0.29         2
          22       0.50      0.50      0.50         6
          23       0.33      0.25      0.29         8
          24       0.00      0.00      0.00         8
          25       0.25      0.25      0.25         4
          26       0.17      0.50      0.25         2
          27       0.00      0.00      0.00         1
          28       0.33      0.40      0.36         5
          29       0.50      0.33      0.40         3
          30       0.67      0.40      0.50         5
          31       0.00      0.00      0.00         5
          32       0.00      0.00      0.00         0
          33       0.50      0.40      0.44         5
          34       0.50      0.60      0.55         5

    accuracy                           0.27       147
   macro avg       0.26      0.27      0.25       147
weighted avg       0.30      0.27      0.27       147


Confusion matrix:
 [[0 0 0 ... 1 0 0]
 [0 2 0 ... 0 1 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 1 0 3]]
==================================================


Model =  Support Vector Classifier
Accuracy =  0.2857142857142857

Classification Report :
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       1.00      0.20      0.33         5
           2       1.00      0.17      0.29         6
           3       0.00      0.00      0.00         3
           4       0.04      0.50      0.08         2
           5       1.00      0.29      0.44         7
           6       1.00      0.50      0.67         6
           7       1.00      0.50      0.67         2
           8       1.00      0.67      0.80         3
           9       0.67      0.67      0.67         3
          10       0.50      0.33      0.40         3
          11       0.50      0.25      0.33         4
          12       0.00      0.00      0.00         6
          13       1.00      0.14      0.25         7
          14       0.50      0.20      0.29         5
          15       0.12      0.50      0.20         2
          16       1.00      0.67      0.80         3
          17       0.00      0.00      0.00         4
          18       0.67      0.50      0.57         4
          19       0.50      0.60      0.55         5
          20       1.00      0.14      0.25         7
          21       0.00      0.00      0.00         2
          22       1.00      0.50      0.67         6
          23       1.00      0.12      0.22         8
          24       0.00      0.00      0.00         8
          25       0.80      1.00      0.89         4
          26       0.00      0.00      0.00         2
          27       0.00      0.00      0.00         1
          28       1.00      0.20      0.33         5
          29       1.00      0.33      0.50         3
          30       0.75      0.60      0.67         5
          31       0.00      0.00      0.00         5
          32       0.00      0.00      0.00         0
          33       0.50      0.20      0.29         5
          34       1.00      0.40      0.57         5

    accuracy                           0.29       147
   macro avg       0.56      0.29      0.33       147
weighted avg       0.65      0.29      0.35       147


Confusion matrix:
 [[0 0 0 ... 1 0 0]
 [1 1 0 ... 0 1 0]
 [2 0 1 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 1 1 0]
 [0 0 0 ... 1 0 2]]
==================================================


Model =  Random Forest Classifier
Accuracy =  0.48299319727891155

Classification Report :
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.43      0.60      0.50         5
           2       0.57      0.67      0.62         6
           3       0.25      0.33      0.29         3
           4       0.00      0.00      0.00         2
           5       0.60      0.43      0.50         7
           6       1.00      0.67      0.80         6
           7       0.50      0.50      0.50         2
           8       0.60      1.00      0.75         3
           9       0.50      0.67      0.57         3
          10       0.40      0.67      0.50         3
          11       0.50      0.25      0.33         4
          12       1.00      0.17      0.29         6
          13       0.25      0.14      0.18         7
          14       0.33      0.60      0.43         5
          15       0.33      0.50      0.40         2
          16       0.60      1.00      0.75         3
          17       0.00      0.00      0.00         4
          18       0.67      0.50      0.57         4
          19       1.00      0.80      0.89         5
          20       0.50      0.43      0.46         7
          21       0.67      1.00      0.80         2
          22       1.00      0.67      0.80         6
          23       1.00      0.38      0.55         8
          24       0.00      0.00      0.00         8
          25       0.80      1.00      0.89         4
          26       0.50      1.00      0.67         2
          27       0.00      0.00      0.00         1
          28       0.60      0.60      0.60         5
          29       1.00      0.33      0.50         3
          30       0.80      0.80      0.80         5
          31       0.00      0.00      0.00         5
          32       0.00      0.00      0.00         0
          33       0.40      0.40      0.40         5
          34       1.00      0.80      0.89         5

    accuracy                           0.48       147
   macro avg       0.51      0.48      0.46       147
weighted avg       0.57      0.48      0.49       147


Confusion matrix:
 [[0 1 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [1 0 4 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 2 0]
 [0 0 0 ... 0 1 4]]
==================================================


Model =  K Nearest Neighbors
Accuracy =  0.35374149659863946

Classification Report :
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.25      0.40      0.31         5
           2       0.44      0.67      0.53         6
           3       0.12      0.33      0.18         3
           4       0.00      0.00      0.00         2
           5       0.09      0.14      0.11         7
           6       1.00      0.50      0.67         6
           7       0.20      0.50      0.29         2
           8       0.43      1.00      0.60         3
           9       0.40      0.67      0.50         3
          10       0.60      1.00      0.75         3
          11       0.00      0.00      0.00         4
          12       0.50      0.17      0.25         6
          13       0.00      0.00      0.00         7
          14       0.25      0.20      0.22         5
          15       0.33      0.50      0.40         2
          16       0.67      0.67      0.67         3
          17       0.00      0.00      0.00         4
          18       0.67      0.50      0.57         4
          19       0.62      1.00      0.77         5
          20       1.00      0.14      0.25         7
          21       0.25      0.50      0.33         2
          22       1.00      0.50      0.67         6
          23       1.00      0.38      0.55         8
          24       0.00      0.00      0.00         8
          25       0.33      0.25      0.29         4
          26       0.00      0.00      0.00         2
          27       0.00      0.00      0.00         1
          28       0.67      0.40      0.50         5
          29       0.50      0.67      0.57         3
          30       0.80      0.80      0.80         5
          31       0.00      0.00      0.00         5
          32       0.00      0.00      0.00         0
          33       0.50      0.40      0.44         5
          34       1.00      0.20      0.33         5

    accuracy                           0.35       147
   macro avg       0.39      0.36      0.33       147
weighted avg       0.46      0.35      0.35       147


Confusion matrix:
 [[0 0 0 ... 0 0 0]
 [0 2 0 ... 0 1 0]
 [1 0 4 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 2 0]
 [0 1 0 ... 0 0 1]]
==================================================


Model =  Decision Tree Classifier
Accuracy =  0.17006802721088435

Classification Report :
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.67      0.40      0.50         5
           2       1.00      0.33      0.50         6
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         2
           5       0.20      0.14      0.17         7
           6       0.00      0.00      0.00         6
           7       0.20      0.50      0.29         2
           8       0.00      0.00      0.00         3
           9       0.00      0.00      0.00         3
          10       0.50      0.67      0.57         3
          11       0.00      0.00      0.00         4
          12       0.00      0.00      0.00         6
          13       0.25      0.14      0.18         7
          14       0.14      0.20      0.17         5
          15       0.00      0.00      0.00         2
          16       0.20      0.33      0.25         3
          17       0.00      0.00      0.00         4
          18       0.17      0.25      0.20         4
          19       0.57      0.80      0.67         5
          20       0.25      0.14      0.18         7
          21       0.00      0.00      0.00         2
          22       0.33      0.17      0.22         6
          23       0.25      0.12      0.17         8
          24       0.00      0.00      0.00         8
          25       0.00      0.00      0.00         4
          26       0.00      0.00      0.00         2
          27       0.00      0.00      0.00         1
          28       0.00      0.00      0.00         5
          29       0.50      0.33      0.40         3
          30       0.60      0.60      0.60         5
          31       0.00      0.00      0.00         5
          32       0.00      0.00      0.00         0
          33       0.00      0.00      0.00         5
          34       0.29      0.40      0.33         5

    accuracy                           0.17       147
   macro avg       0.17      0.16      0.15       147
weighted avg       0.21      0.17      0.18       147


Confusion matrix:
 [[0 0 0 ... 0 0 0]
 [0 2 0 ... 1 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 2]]
==================================================


Model =  Gaussian Naive Bayes
Accuracy =  0.1360544217687075

Classification Report :
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         5
           2       0.27      0.50      0.35         6
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         2
           5       0.00      0.00      0.00         7
           6       0.00      0.00      0.00         6
           7       0.00      0.00      0.00         2
           8       0.06      0.67      0.11         3
           9       0.50      0.67      0.57         3
          10       0.33      0.33      0.33         3
          11       0.00      0.00      0.00         4
          12       0.00      0.00      0.00         6
          13       0.00      0.00      0.00         7
          14       0.00      0.00      0.00         5
          15       0.00      0.00      0.00         2
          16       1.00      0.33      0.50         3
          17       0.00      0.00      0.00         4
          18       0.00      0.00      0.00         4
          19       0.08      0.40      0.14         5
          20       1.00      0.14      0.25         7
          21       0.00      0.00      0.00         2
          22       0.50      0.17      0.25         6
          23       0.11      0.38      0.17         8
          24       0.00      0.00      0.00         8
          25       0.00      0.00      0.00         4
          26       0.00      0.00      0.00         2
          27       0.00      0.00      0.00         1
          28       0.00      0.00      0.00         5
          29       0.07      0.33      0.12         3
          30       0.00      0.00      0.00         5
          31       0.00      0.00      0.00         5
          32       0.00      0.00      0.00         0
          33       0.67      0.40      0.50         5
          34       1.00      0.20      0.33         5

    accuracy                           0.14       147
   macro avg       0.16      0.13      0.10       147
weighted avg       0.18      0.14      0.11       147


Confusion matrix:
 [[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [2 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 2 0]
 [0 0 0 ... 1 0 1]]
==================================================


Model =  AdaBoost Classifier
Accuracy =  0.027210884353741496

Classification Report :
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         5
           2       0.00      0.00      0.00         6
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         2
           5       0.00      0.00      0.00         7
           6       0.00      0.00      0.00         6
           7       0.00      0.00      0.00         2
           8       0.00      0.00      0.00         3
           9       0.00      0.00      0.00         3
          10       0.00      0.00      0.00         3
          11       0.00      0.00      0.00         4
          12       0.00      0.00      0.00         6
          13       0.00      0.00      0.00         7
          14       0.00      0.00      0.00         5
          15       0.00      0.00      0.00         2
          16       0.00      0.00      0.00         3
          17       0.00      0.00      0.00         4
          18       0.25      0.25      0.25         4
          19       0.00      0.00      0.00         5
          20       0.00      0.00      0.00         7
          21       0.00      0.00      0.00         2
          22       0.00      0.00      0.00         6
          23       0.00      0.00      0.00         8
          24       0.00      0.00      0.00         8
          25       0.20      0.50      0.29         4
          26       0.00      0.00      0.00         2
          27       0.00      0.00      0.00         1
          28       0.07      0.20      0.11         5
          29       0.00      0.00      0.00         3
          30       0.00      0.00      0.00         5
          31       0.00      0.00      0.00         5
          32       0.00      0.00      0.00         0
          33       0.00      0.00      0.00         5
          34       0.00      0.00      0.00         5

    accuracy                           0.03       147
   macro avg       0.01      0.03      0.02       147
weighted avg       0.01      0.03      0.02       147


Confusion matrix:
 [[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [2 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
==================================================


Model =  Gradient Boosting Classifier
Accuracy =  0.36054421768707484

Classification Report :
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      0.40      0.44         5
           2       0.75      0.50      0.60         6
           3       0.20      0.33      0.25         3
           4       0.17      0.50      0.25         2
           5       0.50      0.43      0.46         7
           6       0.67      0.33      0.44         6
           7       0.33      0.50      0.40         2
           8       0.29      0.67      0.40         3
           9       0.50      0.67      0.57         3
          10       0.50      0.67      0.57         3
          11       0.50      0.50      0.50         4
          12       0.25      0.17      0.20         6
          13       0.00      0.00      0.00         7
          14       0.20      0.20      0.20         5
          15       0.20      0.50      0.29         2
          16       1.00      0.67      0.80         3
          17       0.00      0.00      0.00         4
          18       0.29      0.50      0.36         4
          19       1.00      0.40      0.57         5
          20       0.00      0.00      0.00         7
          21       0.00      0.00      0.00         2
          22       0.57      0.67      0.62         6
          23       0.50      0.38      0.43         8
          24       0.00      0.00      0.00         8
          25       0.50      0.75      0.60         4
          26       0.33      0.50      0.40         2
          27       0.00      0.00      0.00         1
          28       0.25      0.20      0.22         5
          29       0.14      0.33      0.20         3
          30       0.57      0.80      0.67         5
          31       0.00      0.00      0.00         5
          32       0.00      0.00      0.00         0
          33       0.40      0.40      0.40         5
          34       0.44      0.80      0.57         5

    accuracy                           0.36       147
   macro avg       0.33      0.36      0.33       147
weighted avg       0.36      0.36      0.34       147


Confusion matrix:
 [[0 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 2 0]
 [0 0 0 ... 0 0 4]]
==================================================


Model =  XGBoost Classifier
Accuracy =  0.3469387755102041

Classification Report :
               precision    recall  f1-score   support

           0       0.20      1.00      0.33         1
           1       0.40      0.40      0.40         5
           2       1.00      0.50      0.67         6
           3       0.17      0.33      0.22         3
           4       0.20      0.50      0.29         2
           5       0.75      0.43      0.55         7
           6       0.60      0.50      0.55         6
           7       0.50      0.50      0.50         2
           8       0.25      0.67      0.36         3
           9       0.50      0.67      0.57         3
          10       0.33      0.67      0.44         3
          11       0.00      0.00      0.00         4

In [21]:
model = RandomForestClassifier()

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print("Accuracy score: ", accuracy_score(y_test, y_pred))
print("Report: ", classification_report(y_test, y_pred))
print("Confusion Matrix: ", confusion_matrix(y_test, y_pred))

Accuracy score:  0.4217687074829932
Report:                precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      0.60      0.67         5
           2       0.67      0.67      0.67         6
           3       0.25      0.33      0.29         3
           4       0.00      0.00      0.00         2
           5       0.60      0.43      0.50         7
           6       0.75      0.50      0.60         6
           7       0.33      0.50      0.40         2
           8       0.67      0.67      0.67         3
           9       0.40      0.67      0.50         3
          10       0.33      0.67      0.44         3
          11       0.00      0.00      0.00         4
          12       1.00      0.17      0.29         6
          13       0.40      0.29      0.33         7
          14       0.50      0.60      0.55         5
          15       0.17      0.50      0.25         2
          16       1.00      1.00      1.00         3
          17       0.00      0.00      0.00         4
          18       0.50      0.50      0.50         4
          19       1.00      0.60      0.75         5
          20       0.25      0.14      0.18         7
          21       0.50      1.00      0.67         2
          22       1.00      0.67      0.80         6
          23       0.60      0.38      0.46         8
          24       0.00      0.00      0.00         8
          25       0.43      0.75      0.55         4
          26       0.67      1.00      0.80         2
          27       0.00      0.00      0.00         1
          28       1.00      0.20      0.33         5
          29       0.20      0.33      0.25         3
          30       0.67      0.80      0.73         5
          31       0.00      0.00      0.00         5
          32       0.00      0.00      0.00         0
          33       0.40      0.40      0.40         5
          34       0.75      0.60      0.67         5

    accuracy                           0.42       147
   macro avg       0.45      0.43      0.41       147
weighted avg       0.51      0.42      0.43       147

Confusion Matrix:  [[0 0 0 ... 0 0 0]
 [0 3 0 ... 0 1 0]
 [1 0 4 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 2 0]
 [0 0 0 ... 0 0 3]]

In [22]:
print("Predicted Labels: ", model.predict(X_test_scaled[10].reshape(1, -1))[0])
print("Actual predictions", y_test.iloc[10])

Predicted Labels:  13
Actual predictions 11

In [23]:
print("Predicted Labels: ", model.predict(X_test_scaled[100].reshape(1, -1))[0])
print("Actual predictions", y_test.iloc[100])

Predicted Labels:  22
Actual predictions 22

In [24]:
print("Predicted Labels: ", model.predict(X_test_scaled[120].reshape(1, -1))[0])
print("Actual predictions", y_test.iloc[120])

Predicted Labels:  23
Actual predictions 13

In [25]:
import pickle

#writing to the file
pickle.dump(scaler, open("Models/scaler1.pkl", "wb"))
pickle.dump(model, open("Models/model1.pkl", "wb"))

In [26]:
# reading the file
scaler = pickle.load(open("Models/scaler1.pkl", "rb"))
model = pickle.load(open("Models/model1.pkl", "rb"))

In [27]:
import numpy as np

class_names = ['BBA- Bachelor of Business Administration',
    'BEM- Bachelor of Event Management',
    'Integrated Law Course- BA + LL.B',
    'BJMC- Bachelor of Journalism and Mass Communication',
    'BFD- Bachelor of Fashion Designing',
    'BBS- Bachelor of Business Studies',
    'BTTM- Bachelor of Travel and Tourism Management',
    'BVA- Bachelor of Visual Arts', 
    'BA in History',
    'B.Arch- Bachelor of Architecture',
    'BCA- Bachelor of Computer Applications',
    'B.Sc.- Information Technology', 
    'B.Sc- Nursing',
    'BPharma- Bachelor of Pharmacy', 
    'BDS- Bachelor of Dental Surgery',
    'Animation, Graphics and Multimedia', 
    'B.Sc- Applied Geology',
    'B.Sc.- Physics', 
    'B.Sc. Chemistry',
    'B.Sc. Mathematics',
    'B.Tech.-Civil Engineering',
    'B.Tech.-Computer Science and Engineering',
    'B.Tech.-Electronics and Communication Engineering',
    'B.Tech.-Electrical and Electronics Engineering',
    'B.Tech.-Mechanical Engineering', 
    'B.Com- Bachelor of Commerce',
    'BA in Economics', 
    'CA- Chartered Accountancy',
    'CS- Company Secretary', 
    'Diploma in Dramatic Arts', 
    'MBBS',
    'Civil Services', 
    'BA in English', 
    'BA in Hindi', 
    'B.Ed.']


def Recommendations(Drawing, Dancing, Singing, Sports, VideoGame, Acting, Travelling, Gardening, Animals, 
                    Photography, Teaching, Exercise, Coding, ElectricityComponents, MechanicParts, 
                    ComputerParts, Researching, Architecture, HistoricCollection, Botany, Zoology, Physics, Accounting, 
                    Economics, Sociology, Geography, Psycology, History, Science, BussinessEducation, Chemistry, Mathematics, 
                    Biology, Makeup, Designing, ContentWriting, Crafting, Literature, Reading, Cartooning, Debating, Astrology, 
                    Hindi, French, English, Urdu, OtherLanguage, SolvingPuzzles, Gymnastics, Yoga, Engeeniering, Doctor, 
                    Pharmisist, Cycling, Knitting, Director, Journalism, Bussiness, ListeningMusic):

    # Create feature array
    feature_array = np.array([[Drawing, Dancing, Singing, Sports, VideoGame, Acting, Travelling, Gardening, Animals, 
                               Photography, Teaching, Exercise, Coding, ElectricityComponents, MechanicParts, 
                               ComputerParts, Researching, Architecture, HistoricCollection, Botany, Zoology, 
                               Physics, Accounting, Economics, Sociology, Geography, Psycology, History, Science, 
                               BussinessEducation, Chemistry, Mathematics, Biology, Makeup, Designing, ContentWriting, 
                               Crafting, Literature, Reading, Cartooning, Debating, Astrology, Hindi, French, English, 
                               Urdu, OtherLanguage, SolvingPuzzles, Gymnastics, Yoga, Engeeniering, Doctor, Pharmisist, 
                               Cycling, Knitting, Director, Journalism, Bussiness, ListeningMusic]])

    # Scale features
    scaled_features = scaler.transform(feature_array)

    # Predict using the model
    probabilities = model.predict_proba(scaled_features)

    # Get top five predicted classes along with their probabilities 
    top_classes_idx = np.argsort(-probabilities[0])[:5]   

    top_classes_name_probs = [(class_names[idx], probabilities[0][idx]) for idx in top_classes_idx]

    return top_classes_name_probs

In [28]:
final_recommendations = Recommendations(
    Drawing=1,
    Dancing=0,
    Singing=1,
    Sports=0,
    VideoGame=1,
    Acting=0,
    Travelling=1,
    Gardening=0,
    Animals=1,
    Photography=0,
    Teaching=1,
    Exercise=0,
    Coding=1,
    ElectricityComponents=0,
    MechanicParts=0,
    ComputerParts=1,
    Researching=1,
    Architecture=0,
    HistoricCollection=0,
    Botany=0,
    Zoology=0,
    Physics=1,
    Accounting=0,
    Economics=1,
    Sociology=0,
    Geography=0,
    Psycology=1,
    History=0,
    Science=1,
    BussinessEducation=0,
    Chemistry=1,
    Mathematics=1,
    Biology=0,
    Makeup=0,
    Designing=1,
    ContentWriting=0,
    Crafting=0,
    Literature=1,
    Reading=1,
    Cartooning=0,
    Debating=1,
    Astrology=0,
    Hindi=0,
    French=0,
    English=1,
    Urdu=0,
    OtherLanguage=0,
    SolvingPuzzles=1,
    Gymnastics=0,
    Yoga=1,
    Engeeniering=1,
    Doctor=0,
    Pharmisist=0,
    Cycling=1,
    Knitting=0,
    Director=0,
    Journalism=1,
    Bussiness=1,
    ListeningMusic=1
)

print("Top recommended studies with probabilities : ")
print("=="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")

Top recommended studies with probabilities :
====================================================================================================
Diploma in Dramatic Arts with probability 0.07
Civil Services with probability 0.06
BEM- Bachelor of Event Management with probability 0.05
BJMC- Bachelor of Journalism and Mass Communication with probability 0.05
BFD- Bachelor of Fashion Designing with probability 0.05

In [29]:
input_data = {
    'Drawing': 1,
    'Dancing': 0,
    'Singing': 1,
    'Sports': 0,
    'VideoGame': 1,
    'Acting': 0,
    'Travelling': 1,
    'Gardening': 0,
    'Animals': 1,
    'Photography': 0,
    'Teaching': 1,
    'Exercise': 0,
    'Coding': 1,
    'ElectricityComponents': 0,
    'MechanicParts': 0,
    'ComputerParts': 1,
    'Researching': 1,
    'Architecture': 0,
    'HistoricCollection': 0,
    'Botany': 0,
    'Zoology': 0,
    'Physics': 1,
    'Accounting': 0,
    'Economics': 1,
    'Sociology': 0,
    'Geography': 0,
    'Psycology': 1,
    'History': 0,
    'Science': 1,
    'BussinessEducation': 0,
    'Chemistry': 1,
    'Mathematics': 1,
    'Biology': 0,
    'Makeup': 0,
    'Designing': 1,
    'ContentWriting': 0,
    'Crafting': 0,
    'Literature': 1,
    'Reading': 1,
    'Cartooning': 0,
    'Debating': 1,
    'Astrology': 0,
    'Hindi': 0,
    'French': 0,
    'English': 1,
    'Urdu': 0,
    'OtherLanguage': 0,
    'SolvingPuzzles': 1,
    'Gymnastics': 0,
    'Yoga': 1,
    'Engeeniering': 1,
    'Doctor': 0,
    'Pharmisist': 0,
    'Cycling': 1,
    'Knitting': 0,
    'Director': 0,
    'Journalism': 1,
    'Bussiness': 1,
    'ListeningMusic': 1
}

# Get recommendation from your model
final_recommendations = Recommendations(**input_data)


top_course = final_recommendations[0][0]  # course name
input_data['Courses'] = top_course

# Convert to a DataFrame
df = pd.DataFrame([input_data])

# Save to CSV (append if exists, or create new)
csv_path = 'dataset/stud_testing_final_updated.csv'
try:
    existing_df = pd.read_csv(csv_path)
    updated_df = pd.concat([existing_df, df], ignore_index=True)
except FileNotFoundError:
    print("File not found, creating new")
    updated_df = df

# Save back to CSV
updated_df.to_csv(csv_path, index=False)

print("Prediction saved successfully!")

Prediction saved successfully!