In [1]:
import pandas as pd
data = pd.read_csv("dataset/student-scores.csv")
data
df = data.copy()
df[:8]

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76
5,6,Kelly,Wade,kelly.wade.6@gslingacademy.com,female,False,2,False,26,Unknown,93,100,67,78,72,80,84
6,7,Anthony,Smith,anthony.smith.7@gslingacademy.com,male,False,3,True,23,Software Engineer,99,96,97,73,88,76,64
7,8,George,Short,george.short.8@gslingacademy.com,male,True,2,True,34,Software Engineer,95,95,82,63,84,70,85

In [2]:
df.drop(columns=['id', 'first_name', 'last_name', 'email'], axis=1, inplace=True)

In [3]:
#df.columns

In [4]:
df['total_score'] = df['math_score']+df['history_score']+df['physics_score']+df['chemistry_score']+df['biology_score']+df['english_score']+df['geography_score'] 
df['average_score'] = df['total_score']/7
df.head()

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,average_score
0,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87,574,82.000000
1,female,False,2,False,47,Doctor,90,86,96,100,90,88,90,640,91.428571
2,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94,605,86.428571
3,female,False,5,False,3,Artist,71,74,88,80,89,63,86,551,78.714286
4,male,False,5,False,10,Unknown,84,77,65,65,80,74,76,521,74.428571

In [5]:
df['career_aspiration'].value_counts()

career_aspiration
Software Engineer        315
Business Owner           309
Unknown                  223
Banker                   169
Lawyer                   138
Accountant               126
Doctor                   119
Real Estate Developer     83
Stock Investor            73
Construction Engineer     68
Artist                    67
Game Developer            63
Government Officer        61
Teacher                   59
Designer                  56
Scientist                 39
Writer                    32
Name: count, dtype: int64

In [6]:
df['career_aspiration'].nunique()

17

## converting to numerical

In [7]:
gender_map = {'male': 0, 'female': 1}
part_time_map = {False: 0, True: 1}
extracurricular_map = {False: 0, True: 1}

df['gender'] = df['gender'].map(gender_map)
df['part_time_job'] = df['part_time_job'].map(part_time_map)
df['extracurricular_activities'] = df['extracurricular_activities'].map(extracurricular_map)

In [8]:
career_aspiration_map = {
        'Lawyer': 0, 'Doctor': 1, 'Government Officer': 2, 'Artist': 3, 'Unknown': 4,
        'Software Engineer': 5, 'Teacher': 6, 'Business Owner': 7, 'Scientist': 8,
        'Banker': 9, 'Writer': 10, 'Accountant': 11, 'Designer': 12,
        'Construction Engineer': 13, 'Game Developer': 14, 'Stock Investor': 15,
        'Real Estate Developer': 16
    }

df['career_aspiration'] = df['career_aspiration'].map(career_aspiration_map)

In [9]:
df.head()

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,average_score
0,0,0,3,0,27,0,73,81,93,97,63,80,87,574,82.000000
1,1,0,2,0,47,1,90,86,96,100,90,88,90,640,91.428571
2,1,0,9,1,13,2,81,97,95,96,65,77,94,605,86.428571
3,1,0,5,0,3,3,71,74,88,80,89,63,86,551,78.714286
4,0,0,5,0,10,4,84,77,65,65,80,74,76,521,74.428571

## Balancing dataset

In [10]:
from imblearn.over_sampling import SMOTE

In [11]:
smote = SMOTE(random_state = 42)

X = df.drop('career_aspiration', axis=1)
y = df['career_aspiration']

X_resampled, y_resampled = smote.fit_resample(X,y)

In [12]:
X_resampled

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,average_score
0,0,0,3,0,27,73,81,93,97,63,80,87,574,82.000000
1,1,0,2,0,47,90,86,96,100,90,88,90,640,91.428571
2,1,0,9,1,13,81,97,95,96,65,77,94,605,86.428571
3,1,0,5,0,3,71,74,88,80,89,63,86,551,78.714286
4,0,0,5,0,10,84,77,65,65,80,74,76,521,74.428571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5350,0,0,1,0,6,81,86,78,89,79,85,86,587,83.950540
5351,0,0,2,0,4,54,64,97,87,95,73,79,552,78.978959
5352,0,0,4,0,3,92,74,77,64,91,66,70,537,76.747030
5353,1,0,1,0,5,91,73,66,88,88,86,68,562,80.363227
5354,0,0,2,0,3,59,67,97,84,97,73,78,558,79.744197

In [13]:
y_resampled

0        0
1        1
2        2
3        3
4        4
        ..
5350    16
5351    16
5352    16
5353    16
5354    16
Name: career_aspiration, Length: 5355, dtype: int64

In [14]:
y_resampled.value_counts()

career_aspiration
0     315
1     315
2     315
3     315
4     315
5     315
6     315
7     315
8     315
9     315
10    315
11    315
12    315
13    315
14    315
15    315
16    315
Name: count, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state = 42)

In [16]:
#X_train.shape

## Feature scaling

In [17]:
from sklearn.preprocessing import StandardScaler
scaler  =StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Training the model

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings("ignore")

In [19]:
models = {
    "Logistic Regression": LogisticRegression(),
    "Support Vector Classifier" : SVC(),
    "Random Forest Classifier": RandomForestClassifier(),
    "K Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Gaussian Naive Bayes" : GaussianNB(),
    "AdaBoost Classifier" : AdaBoostClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    "XGBoost Classifier": XGBClassifier(use_label_encoder=False, eval_metric='mlogloss') 
}

In [20]:
for name, model in models.items():
    print("="*50)
    print("\n\nModel = ", name) 

    model.fit(X_train_scaled, y_train)

    y_pred = model.predict(X_test_scaled)

    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)

    conf_matrix = confusion_matrix(y_test, y_pred)

    print("Accuracy = ", accuracy)
    print("\nClassification Report :\n", classification_rep)
    print("\nConfusion matrix: \n", conf_matrix)

==================================================


Model =  Logistic Regression
Accuracy =  0.48739495798319327

Classification Report :
               precision    recall  f1-score   support

           0       0.45      0.54      0.49        68
           1       0.49      0.62      0.55        72
           2       0.42      0.44      0.43        57
           3       0.52      0.57      0.55        58
           4       0.31      0.17      0.22        66
           5       0.32      0.32      0.32        76
           6       0.58      0.92      0.71        71
           7       0.83      0.90      0.87        61
           8       0.41      0.45      0.43        53
           9       0.29      0.10      0.15        61
          10       0.59      0.71      0.65        63
          11       0.44      0.45      0.45        53
          12       0.31      0.16      0.21        68
          13       0.38      0.49      0.43        55
          14       0.61      0.93      0.74        57
          15       0.37      0.24      0.29        63
          16       0.55      0.32      0.40        69

    accuracy                           0.49      1071
   macro avg       0.46      0.49      0.46      1071
weighted avg       0.46      0.49      0.46      1071


Confusion matrix:
 [[37  4  0  0  0  7  0  0  4  1 10  3  0  2  0  0  0]
 [ 2 45  0  0  0  7  0  0 13  0  0  0  0  5  0  0  0]
 [ 0  0 25  5  1  1  9  1  0  0  2  0  4  1  2  2  4]
 [ 0  0  2 33  0  0  2  1  0  0  0  0  0  0 11  0  9]
 [ 6  5  7  3 11  9  7  1  2  3  0  3  3  2  1  2  1]
 [ 8  9  0  0  1 24  1  0  1  7  1  5  3 12  0  4  0]
 [ 0  0  0  0  1  2 65  0  0  1  2  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0 55  0  0  0  0  0  0  3  0  0]
 [ 4 18  0  0  0  1  0  0 24  0  6  0  0  0  0  0  0]
 [10  1  0  0  3  8  8  0  1  6  2  8  6  6  0  2  0]
 [ 8  2  0  0  1  0  4  0  2  1 45  0  0  0  0  0  0]
 [ 0  1  0  0  4  6  3  0  4  1  0 24  1  3  0  6  0]
 [ 2  2  8  3  5  2  7  0  3  0  4  0 11  6  8  5  2]
 [ 1  2  2  0  3  0  0  0  5  1  1  4  4 27  0  5  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0  0 53  0  1]
 [ 4  3  3  0  5  8  1  2  0  0  2  7  4  7  1 15  1]
 [ 0  0 13 13  0  1  5  6  0  0  1  0  0  0  8  0 22]]
==================================================


Model =  Support Vector Classifier
Accuracy =  0.6470588235294118

Classification Report :
               precision    recall  f1-score   support

           0       0.55      0.62      0.58        68
           1       0.60      0.83      0.70        72
           2       0.60      0.74      0.66        57
           3       0.69      0.86      0.77        58
           4       0.55      0.18      0.27        66
           5       0.41      0.32      0.36        76
           6       0.70      0.93      0.80        71
           7       0.86      0.93      0.90        61
           8       0.65      0.81      0.72        53
           9       0.38      0.33      0.35        61
          10       0.84      0.86      0.85        63
          11       0.82      0.51      0.63        53
          12       0.65      0.51      0.57        68
          13       0.53      0.85      0.65        55
          14       0.77      0.93      0.84        57
          15       0.67      0.44      0.53        63
          16       0.77      0.48      0.59        69

    accuracy                           0.65      1071
   macro avg       0.65      0.66      0.63      1071
weighted avg       0.65      0.65      0.63      1071


Confusion matrix:
 [[42  6  0  0  0  4  0  0  2  4  6  0  0  3  0  1  0]
 [ 1 60  0  0  0  1  0  0  5  0  0  0  1  3  0  1  0]
 [ 0  0 42  2  2  1  4  0  0  0  0  0  2  0  0  3  1]
 [ 0  0  2 50  0  0  0  1  0  0  0  0  0  0  3  0  2]
 [ 5  8  7  1 12  7  5  2  1  7  0  2  4  3  1  1  0]
 [10  7  1  0  1 24  1  1  5 12  0  1  1 11  0  1  0]
 [ 0  0  0  0  0  1 66  0  0  2  1  0  0  0  0  0  1]
 [ 0  0  0  1  0  0  1 57  0  0  0  0  0  0  1  0  1]
 [ 1  8  0  0  0  1  0  0 43  0  0  0  0  0  0  0  0]
 [ 8  1  1  0  0  7  6  1  3 20  1  0  4  5  0  4  0]
 [ 2  1  4  0  0  0  0  0  0  1 54  0  0  1  0  0  0]
 [ 0  3  1  0  3  5  0  1  3  2  1 27  1  3  0  3  0]
 [ 2  1  0  3  2  1  8  0  2  0  1  1 35  4  4  0  4]
 [ 0  3  0  0  0  1  0  0  2  1  0  1  0 47  0  0  0]
 [ 0  0  0  0  0  0  1  2  0  0  0  0  1  0 53  0  0]
 [ 5  2  3  0  2  4  0  0  0  3  0  1  4  9  1 28  1]
 [ 0  0  9 15  0  2  2  1  0  0  0  0  1  0  6  0 33]]
==================================================


Model =  Random Forest Classifier
Accuracy =  0.8291316526610645

Classification Report :
               precision    recall  f1-score   support

           0       0.78      0.88      0.83        68
           1       0.83      1.00      0.91        72
           2       0.71      0.98      0.82        57
           3       0.90      0.95      0.92        58
           4       0.78      0.42      0.55        66
           5       0.54      0.37      0.44        76
           6       0.93      0.99      0.96        71
           7       0.97      0.93      0.95        61
           8       0.77      1.00      0.87        53
           9       0.68      0.69      0.68        61
          10       0.94      0.95      0.94        63
          11       0.92      0.68      0.78        53
          12       0.92      0.84      0.88        68
          13       0.74      0.95      0.83        55
          14       0.88      0.98      0.93        57
          15       0.91      0.79      0.85        63
          16       0.93      0.81      0.87        69

    accuracy                           0.83      1071
   macro avg       0.83      0.84      0.82      1071
weighted avg       0.83      0.83      0.82      1071


Confusion matrix:
 [[60  3  0  0  1  2  0  0  0  0  0  0  0  1  0  1  0]
 [ 0 72  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 56  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 55  0  0  0  1  0  0  0  0  0  0  2  0  0]
 [ 4  2  8  0 28 10  1  0  2  4  1  0  2  0  1  1  2]
 [ 7  6  0  0  1 28  0  0  5 14  0  1  0 12  0  2  0]
 [ 0  0  0  0  0  1 70  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0 57  0  0  0  0  0  0  2  0  1]
 [ 0  0  0  0  0  0  0  0 53  0  0  0  0  0  0  0  0]
 [ 3  1  3  0  0  3  1  0  2 42  1  1  3  0  0  1  0]
 [ 0  0  2  0  0  0  0  0  1  0 60  0  0  0  0  0  0]
 [ 0  1  0  0  3  6  1  0  3  1  1 36  0  1  0  0  0]
 [ 0  1  3  0  1  1  1  0  0  0  1  1 57  0  1  0  1]
 [ 0  0  2  0  0  0  0  0  1  0  0  0  0 52  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0 56  0  0]
 [ 3  1  1  0  1  1  0  0  1  1  0  0  0  4  0 50  0]
 [ 0  0  4  4  1  0  0  1  1  0  0  0  0  0  2  0 56]]
==================================================


Model =  K Nearest Neighbors
Accuracy =  0.6778711484593838

Classification Report :
               precision    recall  f1-score   support

           0       0.59      0.68      0.63        68
           1       0.73      0.78      0.75        72
           2       0.63      0.86      0.73        57
           3       0.60      0.81      0.69        58
           4       0.35      0.17      0.23        66
           5       0.35      0.14      0.21        76
           6       0.83      0.92      0.87        71
           7       0.90      0.72      0.80        61
           8       0.67      0.91      0.77        53
           9       0.44      0.48      0.46        61
          10       0.81      0.92      0.86        63
          11       0.71      0.64      0.67        53
          12       0.71      0.79      0.75        68
          13       0.69      0.80      0.74        55
          14       0.82      0.89      0.86        57
          15       0.65      0.62      0.63        63
          16       0.78      0.58      0.67        69

    accuracy                           0.68      1071
   macro avg       0.66      0.69      0.67      1071
weighted avg       0.66      0.68      0.66      1071


Confusion matrix:
 [[46  2  0  0  0  3  0  0  1  8  6  0  0  0  0  2  0]
 [ 4 56  0  0  1  0  0  0  4  1  1  0  1  1  0  3  0]
 [ 0  0 49  1  0  0  0  0  0  0  2  0  0  0  1  1  3]
 [ 0  0  4 47  0  0  0  1  0  1  0  0  0  0  3  0  2]
 [ 4  5  5  5 11  6  6  1  2  7  1  1  6  1  1  1  3]
 [10  6  2  0  7 11  1  1  6  9  0  3  6 10  0  4  0]
 [ 0  0  1  2  0  0 65  0  0  2  0  0  0  0  1  0  0]
 [ 0  0  1  3  2  0  1 44  0  2  0  1  2  1  1  1  2]
 [ 1  4  0  0  0  0  0  0 48  0  0  0  0  0  0  0  0]
 [ 6  0  2  1  3  3  1  1  2 29  1  4  4  0  0  3  1]
 [ 2  0  2  0  0  0  0  0  0  1 58  0  0  0  0  0  0]
 [ 0  2  2  0  0  5  0  0  3  2  1 34  1  2  1  0  0]
 [ 1  1  2  2  0  0  1  0  0  2  1  1 54  0  0  3  0]
 [ 2  0  0  0  4  0  0  0  3  0  0  0  0 44  1  1  0]
 [ 0  0  1  1  0  1  0  0  0  0  0  0  1  1 51  1  0]
 [ 2  1  1  4  2  1  1  0  3  2  0  4  0  3  0 39  0]
 [ 0  0  6 12  1  1  2  1  0  0  1  0  1  1  2  1 40]]
==================================================


Model =  Decision Tree Classifier
Accuracy =  0.6909430438842203

Classification Report :
               precision    recall  f1-score   support

           0       0.66      0.71      0.68        68
           1       0.75      0.88      0.81        72
           2       0.71      0.72      0.71        57
           3       0.79      0.78      0.78        58
           4       0.40      0.35      0.37        66
           5       0.40      0.25      0.31        76
           6       0.88      0.83      0.86        71
           7       0.92      0.77      0.84        61
           8       0.79      0.92      0.85        53
           9       0.52      0.52      0.52        61
          10       0.80      0.84      0.82        63
          11       0.58      0.66      0.62        53
          12       0.66      0.75      0.70        68
          13       0.66      0.78      0.72        55
          14       0.83      0.93      0.88        57
          15       0.55      0.46      0.50        63
          16       0.74      0.72      0.73        69

    accuracy                           0.69      1071
   macro avg       0.68      0.70      0.69      1071
weighted avg       0.68      0.69      0.68      1071


Confusion matrix:
 [[48  3  0  0  1  7  0  0  1  0  5  0  1  2  0  0  0]
 [ 2 63  0  0  0  0  0  0  3  0  0  1  1  0  0  2  0]
 [ 0  0 41  0  2  1  0  1  0  3  0  0  4  1  0  1  3]
 [ 0  0  0 45  2  0  0  2  0  0  0  0  1  0  4  0  4]
 [ 3  3  7  0 23  3  1  0  1  6  3  3  3  1  1  3  5]
 [ 9  7  0  0 10 19  1  0  2  6  1  7  4  7  0  3  0]
 [ 0  0  1  0  3  3 59  0  0  2  1  0  2  0  0  0  0]
 [ 0  0  0  3  3  0  0 47  0  0  0  0  2  0  4  0  2]
 [ 1  2  0  0  0  0  0  0 49  0  1  0  0  0  0  0  0]
 [ 5  0  0  0  2  4  2  0  2 32  2  5  2  1  0  4  0]
 [ 0  1  0  0  0  1  0  0  2  4 53  0  1  1  0  0  0]
 [ 0  2  0  0  3  2  2  0  2  1  0 35  3  0  0  3  0]
 [ 0  1  2  1  3  1  1  0  0  3  0  0 51  0  1  2  2]
 [ 3  1  1  0  1  0  0  0  0  1  0  1  0 43  0  4  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  2  0 53  0  1]
 [ 2  1  4  0  1  5  0  0  0  3  0  8  0  9  0 29  1]
 [ 0  0  2  7  3  1  1  1  0  1  0  0  0  0  1  2 50]]
==================================================


Model =  Gaussian Naive Bayes
Accuracy =  0.3099906629318394

Classification Report :
               precision    recall  f1-score   support

           0       0.56      0.22      0.32        68
           1       0.64      0.53      0.58        72
           2       0.18      0.05      0.08        57
           3       0.30      0.05      0.09        58
           4       0.50      0.06      0.11        66
           5       0.45      0.18      0.26        76
           6       0.31      1.00      0.47        71
           7       0.95      0.85      0.90        61
           8       0.64      0.17      0.27        53
           9       0.20      0.03      0.06        61
          10       0.69      0.35      0.46        63
          11       0.60      0.23      0.33        53
          12       0.50      0.13      0.21        68
          13       0.11      0.96      0.20        55
          14       0.00      0.00      0.00        57
          15       0.50      0.06      0.11        63
          16       0.47      0.30      0.37        69

    accuracy                           0.31      1071
   macro avg       0.45      0.31      0.28      1071
weighted avg       0.45      0.31      0.29      1071


Confusion matrix:
 [[15  0  0  0  0  3  4  0  1  0  4  2  0 39  0  0  0]
 [ 0 38  0  0  0  2  3  0  3  0  0  0  2 24  0  0  0]
 [ 0  0  3  0  1  1 16  0  0  0  0  0  0 31  0  2  3]
 [ 0  0  0  3  0  0 15  1  0  0  0  0  0 23  3  0 13]
 [ 3  3  0  3  4  3 13  0  0  2  0  3  3 26  0  0  3]
 [ 4  6  0  0  1 14 12  0  0  2  0  1  1 34  0  1  0]
 [ 0  0  0  0  0  0 71  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  3 52  0  0  0  0  0  3  0  0  2]
 [ 0  3  0  0  0  0  0  0  9  1  1  0  0 39  0  0  0]
 [ 2  1  1  0  1  2 16  0  0  2  4  1  1 30  0  0  0]
 [ 3  6  0  0  0  0  9  0  0  1 22  0  0 22  0  0  0]
 [ 0  0  0  0  0  1 13  0  0  0  0 12  1 25  0  1  0]
 [ 0  1  7  0  0  0 21  0  1  0  1  0  9 27  0  0  1]
 [ 0  1  0  0  0  1  0  0  0  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  0  0 11  1  0  0  0  0  0 45  0  0  0]
 [ 0  0  1  0  1  2  6  0  0  1  0  1  1 44  0  4  2]
 [ 0  0  5  3  0  2 16  1  0  1  0  0  0 20  0  0 21]]
==================================================


Model =  AdaBoost Classifier
Accuracy =  0.21942110177404295

Classification Report :
               precision    recall  f1-score   support

           0       0.16      1.00      0.27        68
           1       1.00      0.61      0.76        72
           2       0.00      0.00      0.00        57
           3       0.00      0.00      0.00        58
           4       0.00      0.00      0.00        66
           5       0.00      0.00      0.00        76
           6       0.24      0.37      0.29        71
           7       0.00      0.00      0.00        61
           8       0.00      0.00      0.00        53
           9       0.00      0.00      0.00        61
          10       0.17      0.06      0.09        63
          11       1.00      0.36      0.53        53
          12       0.13      0.28      0.18        68
          13       0.00      0.00      0.00        55
          14       0.00      0.00      0.00        57
          15       0.00      0.00      0.00        63
          16       0.19      0.80      0.30        69

    accuracy                           0.22      1071
   macro avg       0.17      0.20      0.14      1071
weighted avg       0.17      0.22      0.15      1071


Confusion matrix:
 [[68  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [28 44  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  0  0  0  0 27  0  0  0 24]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 58]
 [36  0  0  0  0  0  2  0  0  0  2  0 15  0  0  0 11]
 [62  0  0  0  0  0 10  0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 26  0  0  0  1  0 38  0  0  0  6]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 61]
 [53  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [37  0  0  0  0  0 10  0  0  0  3  0 11  0  0  0  0]
 [51  0  0  0  0  0  6  0  0  0  4  0  2  0  0  0  0]
 [23  0  0  0  0  0  8  0  0  0  1 19  2  0  0  0  0]
 [19  0  0  0  0  0 13  0  0  0  1  0 19  0  0  0 16]
 [25  0  0  0  0  0 16  0  0  0  4  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 57]
 [36  0  0  0  0  0 12  0  0  0  4  0  7  0  0  0  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 14  0  0  0 55]]
==================================================


Model =  Gradient Boosting Classifier
Accuracy =  0.738562091503268

Classification Report :
               precision    recall  f1-score   support

           0       0.69      0.81      0.74        68
           1       0.80      0.96      0.87        72
           2       0.60      0.86      0.71        57
           3       0.78      0.91      0.84        58
           4       0.50      0.17      0.25        66
           5       0.46      0.42      0.44        76
           6       0.82      0.99      0.90        71
           7       0.97      0.95      0.96        61
           8       0.76      0.98      0.86        53
           9       0.54      0.43      0.48        61
          10       0.88      0.95      0.92        63
          11       0.72      0.58      0.65        53
          12       0.75      0.60      0.67        68
          13       0.64      0.85      0.73        55
          14       0.89      0.98      0.93        57
          15       0.74      0.56      0.64        63
          16       0.85      0.67      0.75        69

    accuracy                           0.74      1071
   macro avg       0.73      0.75      0.73      1071
weighted avg       0.73      0.74      0.72      1071


Confusion matrix:
 [[55  3  0  0  1  5  0  0  0  1  0  1  1  1  0  0  0]
 [ 1 69  0  0  0  1  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0 49  1  0  1  3  0  0  0  0  0  0  0  0  0  3]
 [ 0  0  0 53  0  0  0  1  0  0  0  0  1  0  2  0  1]
 [ 4  4 12  2 11 10  1  0  2  5  2  2  4  3  1  2  1]
 [10  2  0  0  2 32  1  0  3  9  1  2  0 12  0  2  0]
 [ 0  0  1  0  0  0 70  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  0  0  0 58  0  0  0  0  0  0  1  0  0]
 [ 0  1  0  0  0  0  0  0 52  0  0  0  0  0  0  0  0]
 [ 3  0  3  0  1  4  4  0  4 26  4  3  2  3  0  4  0]
 [ 2  1  0  0  0  0  0  0  0  0 60  0  0  0  0  0  0]
 [ 1  3  1  0  1  4  3  0  3  4  0 31  0  2  0  0  0]
 [ 1  0  6  2  1  3  1  0  1  1  1  1 41  3  2  2  2]
 [ 1  1  2  0  0  1  0  0  1  0  0  0  0 47  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0 56  0  0]
 [ 2  2  2  0  3  8  0  0  1  2  0  3  1  3  0 35  1]
 [ 0  0  5  8  2  0  2  1  0  0  0  0  4  0  1  0 46]]
==================================================


Model =  XGBoost Classifier
Accuracy =  0.8272642390289449

Classification Report :
               precision    recall  f1-score   support

           0       0.78      0.85      0.82        68
           1       0.83      0.94      0.88        72
           2       0.81      0.91      0.86        57
           3       0.87      0.91      0.89        58
           4       0.88      0.42      0.57        66
           5       0.55      0.42      0.48        76
           6       0.92      0.97      0.95        71
           7       0.95      0.93      0.94        61
           8       0.84      1.00      0.91        53
           9       0.61      0.70      0.66        61
          10       0.98      0.97      0.98        63
          11       0.75      0.72      0.73        53
          12       0.91      0.93      0.92        68
          13       0.75      0.91      0.82        55
          14       0.92      0.98      0.95        57
          15       0.78      0.71      0.74        63
          16       0.94      0.87      0.90        69

    accuracy                           0.83      1071
   macro avg       0.83      0.83      0.82      1071
weighted avg       0.83      0.83      0.82      1071


Confusion matrix:
 [[58  3  0  0  2  1  0  0  0  1  0  1  0  1  0  1  0]
 [ 1 68  0  0  0  0  0  0  1  1  0  0  1  0  0  0  0]
 [ 0  0 52  0  0  1  1  0  0  1  0  0  1  0  0  0  1]
 [ 0  0  0 53  0  0  0  1  0  0  0  0  0  0  2  0  2]
 [ 4  3  6  0 28  9  2  0  2  6  1  0  2  0  1  2  0]
 [ 8  4  0  0  0 32  0  0  2 10  0  4  0 11  0  5  0]
 [ 0  0  0  0  0  0 69  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0 57  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0 53  0  0  0  0  0  0  0  0]
 [ 1  0  2  0  0  4  1  0  2 43  0  3  2  0  0  3  0]
 [ 0  0  0  0  0  0  0  0  1  0 61  0  0  1  0  0  0]
 [ 1  2  0  0  0  4  2  0  2  3  0 38  0  1  0  0  0]
 [ 0  1  1  0  0  0  0  0  0  0  0  1 63  0  2  0  0]
 [ 0  0  1  0  0  2  0  0  0  0  0  0  0 50  0  2  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0 56  0  0]
 [ 1  1  0  0  1  5  0  0  0  3  0  4  0  3  0 45  0]
 [ 0  0  2  5  1  0  0  1  0  0  0  0  0  0  0  0 60]]

## selecting random forect model

In [21]:
model = RandomForestClassifier()

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print("Accuracy score: ", accuracy_score(y_test, y_pred))
print("Report: ", classification_report(y_test, y_pred))
print("Confusion Matrix: ", confusion_matrix(y_test, y_pred))

Accuracy score:  0.830999066293184
Report:                precision    recall  f1-score   support

           0       0.79      0.88      0.83        68
           1       0.81      0.99      0.89        72
           2       0.75      1.00      0.86        57
           3       0.89      0.95      0.92        58
           4       0.77      0.41      0.53        66
           5       0.59      0.38      0.46        76
           6       0.95      1.00      0.97        71
           7       0.93      0.92      0.93        61
           8       0.73      0.98      0.84        53
           9       0.68      0.70      0.69        61
          10       0.94      0.94      0.94        63
          11       0.90      0.72      0.80        53
          12       0.87      0.87      0.87        68
          13       0.78      0.91      0.84        55
          14       0.90      0.98      0.94        57
          15       0.89      0.79      0.84        63
          16       0.93      0.83      0.88        69

    accuracy                           0.83      1071
   macro avg       0.83      0.84      0.83      1071
weighted avg       0.83      0.83      0.82      1071

Confusion Matrix:  [[60  4  0  0  1  1  0  0  0  1  0  0  0  0  0  1  0]
 [ 0 71  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0 57  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 55  0  0  0  1  0  0  0  0  0  0  2  0  0]
 [ 5  2  8  0 27  9  0  0  2  4  1  0  3  0  1  2  2]
 [ 6  6  0  0  2 29  1  0  5 10  0  2  2 11  0  2  0]
 [ 0  0  0  0  0  0 71  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  0  0 56  0  0  0  0  0  0  2  0  1]
 [ 0  1  0  0  0  0  0  0 52  0  0  0  0  0  0  0  0]
 [ 2  1  1  0  0  4  2  0  2 43  2  1  3  0  0  0  0]
 [ 1  0  2  0  0  0  0  0  1  0 59  0  0  0  0  0  0]
 [ 0  3  0  0  3  3  0  0  3  2  0 38  0  1  0  0  0]
 [ 0  0  2  0  1  0  1  0  1  1  1  0 59  0  1  0  1]
 [ 0  0  1  0  0  0  0  0  3  0  0  0  0 50  0  1  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0 56  0  0]
 [ 2  0  2  0  0  3  0  0  1  2  0  1  0  2  0 50  0]
 [ 0  0  3  6  0  0  0  2  1  0  0  0  0  0  0  0 57]]

## Single input predictions

In [22]:
print("Predicted Labels: ", model.predict(X_test_scaled[10].reshape(1, -1))[0])
print("Actual predictions", y_test.iloc[10])

Predicted Labels:  12
Actual predictions 12

In [23]:
print("Predicted Labels: ", model.predict(X_test_scaled[100].reshape(1, -1))[0])
print("Actual predictions", y_test.iloc[100])

Predicted Labels:  12
Actual predictions 12

In [24]:
print("Predicted Labels: ", model.predict(X_test_scaled[400].reshape(1, -1))[0])
print("Actual predictions", y_test.iloc[400])

Predicted Labels:  0
Actual predictions 0

## Saving and loading files

In [25]:
import pickle

#writing to the file
pickle.dump(scaler, open("Models/scaler.pkl", "wb"))
pickle.dump(model, open("Models/model.pkl", "wb"))

In [26]:
# reading the file
scaler = pickle.load(open("Models/scaler.pkl", "rb"))
model = pickle.load(open("Models/model.pkl", "rb"))

## Recommendation System

In [27]:
import sklearn
print(sklearn.__version__)

1.6.1

In [28]:
class_names = ['Lawyer', 'Doctor', 'Government Officer', 'Artist', 'Unknown',
               'Software Engineer', 'Teacher', 'Business Owner', 'Scientist',
               'Banker', 'Writer', 'Accountant', 'Designer',
               'Construction Engineer', 'Game Developer', 'Stock Investor',
               'Real Estate Developer']

import numpy as np
def Recommendations(gender,	part_time_job, absence_days, extracurricular_activities, weekly_self_study_hours, math_score, history_score, physics_score,	
                    chemistry_score, biology_score, english_score, geography_score, total_score, average_score):

    #encoding categorical variables
    gender_encoded = 1 if gender.lower() == 'female' else 0
    part_time_job_encoded = 1 if part_time_job else 0
    extracurricular_activities_encoded = 1 if extracurricular_activities else 0

    #create feature array
    feature_array = np.array([[gender_encoded, part_time_job_encoded, absence_days, extracurricular_activities_encoded, 
                          weekly_self_study_hours, math_score, history_score, physics_score, 
                          chemistry_score, biology_score, english_score, geography_score, 
                          total_score, average_score]])

    #scale features
    scaled_features = scaler.transform(feature_array)

    # Predict using the model
    probabilities = model.predict_proba(scaled_features)

    #get top five predicted classes along with their probabilities 
    top_classes_idx = np.argsort(-probabilities[0])[:5]   

    top_classes_name_probs = [(class_names[idx], probabilities[0][idx]) for idx in top_classes_idx]

    return top_classes_name_probs

In [29]:
final_recommendations = Recommendations(gender='female', 
                                        part_time_job=False, 
                                        absence_days=2, 
                                        extracurricular_activities=True, 
                                        weekly_self_study_hours=10, 
                                        math_score=85, 
                                        history_score=78, 
                                        physics_score=82, 
                                        chemistry_score=88, 
                                        biology_score=90, 
                                        english_score=80, 
                                        geography_score=75, 
                                        total_score=578, 
                                        average_score=82.5714286)

print("Top recommended studies with probabilities : ")
print("=="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")

Top recommended studies with probabilities :
====================================================================================================
Teacher with probability 0.26
Real Estate Developer with probability 0.17
Government Officer with probability 0.14
Banker with probability 0.13
Software Engineer with probability 0.08

In [30]:
final_recommendations = Recommendations(gender='female',
                                        part_time_job=False,
                                        absence_days=2,
                                        extracurricular_activities=False,
                                        weekly_self_study_hours=4,
                                        math_score=87,
                                        history_score=73,
                                        physics_score=98,
                                        chemistry_score=91,
                                        biology_score=79,
                                        english_score=60,
                                        geography_score=77,
                                        total_score=583,
                                        average_score=83.285714)

print("Top recommended studies with probabilities:")
print("="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")

Top recommended studies with probabilities:
==================================================
Artist with probability 0.64
Game Developer with probability 0.14
Real Estate Developer with probability 0.06
Business Owner with probability 0.05
Stock Investor with probability 0.02

In [31]:
final_recommendations = Recommendations(gender='female',
                                        part_time_job=False,
                                        absence_days=2,
                                        extracurricular_activities=False,
                                        weekly_self_study_hours=7,
                                        math_score=65,
                                        history_score=60,
                                        physics_score=97,
                                        chemistry_score=94,
                                        biology_score=71,
                                        english_score=81,
                                        geography_score=66,
                                        total_score=534,
                                        average_score=76.285714)

print("Top recommended studies with probabilities:")
print("="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")

Top recommended studies with probabilities:
==================================================
Teacher with probability 0.68
Unknown with probability 0.11
Government Officer with probability 0.08
Real Estate Developer with probability 0.05
Business Owner with probability 0.03